// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Servofocus
{
    /// <summary>Generic result errors</summary>
    public enum ServoResult
    {
        Ok = 0,
        UnexpectedError = 1,
        WrongThread = 2,
        CantReadStr = 3,
        CantParseUrl = 4
    }

    /// <summary>Scroll state</summary>
    public enum ScrollState
    {
        Start = 0,
        Move = 1,
        End = 2,
        Canceled = 3
    }

    /// <summary>Callback used by Servo internals</summary>
    public unsafe partial class HostCallbacks : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 24)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::System.IntPtr wakeup;

            [FieldOffset(8)]
            internal global::System.IntPtr flush;

            [FieldOffset(16)]
            internal global::System.IntPtr log;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0HostCallbacks@@QEAA@AEBU0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.HostCallbacks> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.HostCallbacks>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.HostCallbacks __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.HostCallbacks(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.HostCallbacks __CreateInstance(global::Servofocus.HostCallbacks.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.HostCallbacks(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.HostCallbacks.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.HostCallbacks.__Internal));
            *(global::Servofocus.HostCallbacks.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private HostCallbacks(global::Servofocus.HostCallbacks.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected HostCallbacks(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public HostCallbacks()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.HostCallbacks.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public HostCallbacks(global::Servofocus.HostCallbacks _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.HostCallbacks.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::Servofocus.HostCallbacks.__Internal*) __Instance) = *((global::Servofocus.HostCallbacks.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.HostCallbacks __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }
    }

    public unsafe partial class Size : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 8)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal uint width;

            [FieldOffset(4)]
            internal uint height;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Size@@QEAA@AEBU0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Size> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Size>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.Size __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.Size(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.Size __CreateInstance(global::Servofocus.Size.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.Size(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.Size.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.Size.__Internal));
            *(global::Servofocus.Size.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private Size(global::Servofocus.Size.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Size(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public Size()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Size.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public Size(global::Servofocus.Size _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Size.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::Servofocus.Size.__Internal*) __Instance) = *((global::Servofocus.Size.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.Size __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public uint Width
        {
            get
            {
                return ((global::Servofocus.Size.__Internal*) __Instance)->width;
            }

            set
            {
                ((global::Servofocus.Size.__Internal*) __Instance)->width = value;
            }
        }

        public uint Height
        {
            get
            {
                return ((global::Servofocus.Size.__Internal*) __Instance)->height;
            }

            set
            {
                ((global::Servofocus.Size.__Internal*) __Instance)->height = value;
            }
        }
    }

    public unsafe partial class Margins : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal uint top;

            [FieldOffset(4)]
            internal uint right;

            [FieldOffset(8)]
            internal uint bottom;

            [FieldOffset(12)]
            internal uint left;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Margins@@QEAA@AEBU0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Margins> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Margins>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.Margins __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.Margins(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.Margins __CreateInstance(global::Servofocus.Margins.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.Margins(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.Margins.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.Margins.__Internal));
            *(global::Servofocus.Margins.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private Margins(global::Servofocus.Margins.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Margins(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public Margins()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Margins.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public Margins(global::Servofocus.Margins _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Margins.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::Servofocus.Margins.__Internal*) __Instance) = *((global::Servofocus.Margins.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.Margins __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public uint Top
        {
            get
            {
                return ((global::Servofocus.Margins.__Internal*) __Instance)->top;
            }

            set
            {
                ((global::Servofocus.Margins.__Internal*) __Instance)->top = value;
            }
        }

        public uint Right
        {
            get
            {
                return ((global::Servofocus.Margins.__Internal*) __Instance)->right;
            }

            set
            {
                ((global::Servofocus.Margins.__Internal*) __Instance)->right = value;
            }
        }

        public uint Bottom
        {
            get
            {
                return ((global::Servofocus.Margins.__Internal*) __Instance)->bottom;
            }

            set
            {
                ((global::Servofocus.Margins.__Internal*) __Instance)->bottom = value;
            }
        }

        public uint Left
        {
            get
            {
                return ((global::Servofocus.Margins.__Internal*) __Instance)->left;
            }

            set
            {
                ((global::Servofocus.Margins.__Internal*) __Instance)->left = value;
            }
        }
    }

    public unsafe partial class Position : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 8)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal int x;

            [FieldOffset(4)]
            internal int y;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Position@@QEAA@AEBU0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Position> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.Position>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.Position __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.Position(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.Position __CreateInstance(global::Servofocus.Position.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.Position(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.Position.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.Position.__Internal));
            *(global::Servofocus.Position.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private Position(global::Servofocus.Position.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Position(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public Position()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Position.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public Position(global::Servofocus.Position _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.Position.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::Servofocus.Position.__Internal*) __Instance) = *((global::Servofocus.Position.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.Position __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public int X
        {
            get
            {
                return ((global::Servofocus.Position.__Internal*) __Instance)->x;
            }

            set
            {
                ((global::Servofocus.Position.__Internal*) __Instance)->x = value;
            }
        }

        public int Y
        {
            get
            {
                return ((global::Servofocus.Position.__Internal*) __Instance)->y;
            }

            set
            {
                ((global::Servofocus.Position.__Internal*) __Instance)->y = value;
            }
        }
    }

    public unsafe partial class ViewLayout : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 36)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::Servofocus.Size.__Internal view_size;

            [FieldOffset(8)]
            internal global::Servofocus.Margins.__Internal margins;

            [FieldOffset(24)]
            internal global::Servofocus.Position.__Internal position;

            [FieldOffset(32)]
            internal float hidpi_factor;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0ViewLayout@@QEAA@AEBU0@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.ViewLayout> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.ViewLayout>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.ViewLayout __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.ViewLayout(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.ViewLayout __CreateInstance(global::Servofocus.ViewLayout.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.ViewLayout(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.ViewLayout.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.ViewLayout.__Internal));
            *(global::Servofocus.ViewLayout.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private ViewLayout(global::Servofocus.ViewLayout.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected ViewLayout(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public ViewLayout()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.ViewLayout.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public ViewLayout(global::Servofocus.ViewLayout _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.ViewLayout.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            *((global::Servofocus.ViewLayout.__Internal*) __Instance) = *((global::Servofocus.ViewLayout.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.ViewLayout __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public global::Servofocus.Size ViewSize
        {
            get
            {
                return global::Servofocus.Size.__CreateInstance(((global::Servofocus.ViewLayout.__Internal*) __Instance)->view_size);
            }

            set
            {
                ((global::Servofocus.ViewLayout.__Internal*) __Instance)->view_size = ReferenceEquals(value, null) ? new global::Servofocus.Size.__Internal() : *(global::Servofocus.Size.__Internal*) value.__Instance;
            }
        }

        public global::Servofocus.Margins Margins
        {
            get
            {
                return global::Servofocus.Margins.__CreateInstance(((global::Servofocus.ViewLayout.__Internal*) __Instance)->margins);
            }

            set
            {
                ((global::Servofocus.ViewLayout.__Internal*) __Instance)->margins = ReferenceEquals(value, null) ? new global::Servofocus.Margins.__Internal() : *(global::Servofocus.Margins.__Internal*) value.__Instance;
            }
        }

        public global::Servofocus.Position Position
        {
            get
            {
                return global::Servofocus.Position.__CreateInstance(((global::Servofocus.ViewLayout.__Internal*) __Instance)->position);
            }

            set
            {
                ((global::Servofocus.ViewLayout.__Internal*) __Instance)->position = ReferenceEquals(value, null) ? new global::Servofocus.Position.__Internal() : *(global::Servofocus.Position.__Internal*) value.__Instance;
            }
        }

        public float HidpiFactor
        {
            get
            {
                return ((global::Servofocus.ViewLayout.__Internal*) __Instance)->hidpi_factor;
            }

            set
            {
                ((global::Servofocus.ViewLayout.__Internal*) __Instance)->hidpi_factor = value;
            }
        }
    }

    public unsafe partial class ServoSharp : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="init_with_egl")]
            internal static extern global::Servofocus.ServoResult InitWithEgl(global::System.IntPtr instance, global::Servofocus.HostCallbacks.__Internal callbacks, global::Servofocus.ViewLayout.__Internal layout);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="perform_updates")]
            internal static extern global::Servofocus.ServoResult PerformUpdates(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="load_url")]
            internal static extern global::Servofocus.ServoResult LoadUrl(global::System.IntPtr instance, byte* url);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="scroll")]
            internal static extern global::Servofocus.ServoResult Scroll(global::System.IntPtr instance, int dx, int dy, uint x, uint y, global::Servofocus.ScrollState state);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libservobridge", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="servo_version")]
            internal static extern byte* ServoVersion(global::System.IntPtr instance);
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.ServoSharp> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::Servofocus.ServoSharp>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::Servofocus.ServoSharp __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::Servofocus.ServoSharp(native.ToPointer(), skipVTables);
        }

        internal static global::Servofocus.ServoSharp __CreateInstance(global::Servofocus.ServoSharp.__Internal native, bool skipVTables = false)
        {
            return new global::Servofocus.ServoSharp(native, skipVTables);
        }

        private static void* __CopyValue(global::Servofocus.ServoSharp.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::Servofocus.ServoSharp.__Internal));
            *(global::Servofocus.ServoSharp.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private ServoSharp(global::Servofocus.ServoSharp.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected ServoSharp(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        public ServoSharp()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::Servofocus.ServoSharp.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::Servofocus.ServoSharp __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        /// <summary>Needs to be called from the EGL thread</summary>
        public global::Servofocus.ServoResult InitWithEgl(global::Servofocus.HostCallbacks callbacks, global::Servofocus.ViewLayout layout)
        {
            var __arg0 = ReferenceEquals(callbacks, null) ? new global::Servofocus.HostCallbacks.__Internal() : *(global::Servofocus.HostCallbacks.__Internal*) callbacks.__Instance;
            var __arg1 = ReferenceEquals(layout, null) ? new global::Servofocus.ViewLayout.__Internal() : *(global::Servofocus.ViewLayout.__Internal*) layout.__Instance;
            var __ret = __Internal.InitWithEgl((__Instance + __PointerAdjustment), __arg0, __arg1);
            return __ret;
        }

        /// <summary>
        /// <para>This is the Servo heartbeat. This needs to be called</para>
        /// <para>everytime wakeup is called.</para>
        /// </summary>
        public global::Servofocus.ServoResult PerformUpdates()
        {
            var __ret = __Internal.PerformUpdates((__Instance + __PointerAdjustment));
            return __ret;
        }

        /// <summary>Load an URL. This needs to be a valid url.</summary>
        public global::Servofocus.ServoResult LoadUrl(byte* url)
        {
            var __ret = __Internal.LoadUrl((__Instance + __PointerAdjustment), url);
            return __ret;
        }

        public global::Servofocus.ServoResult Scroll(int dx, int dy, uint x, uint y, global::Servofocus.ScrollState state)
        {
            var __ret = __Internal.Scroll((__Instance + __PointerAdjustment), dx, dy, x, y, state);
            return __ret;
        }

        public byte* ServoVersion()
        {
            var __ret = __Internal.ServoVersion((__Instance + __PointerAdjustment));
            return __ret;
        }
    }
}
